/**
 * TraceQA Type Definitions
 * Core TypeScript interfaces and types for the TraceQA testing system
 */

// ============================================================================
// Test Configuration Types
// ============================================================================

/**
 * Test type enumeration
 */
export enum TestType {
  WEB_UI = 'ui',
  API = 'api',
  INTEGRATION = 'integration',
  BOTH = 'both'
}

/**
 * Main test configuration interface
 */
export interface TestConfig {
  repository: RepositoryInfo;
  testType: TestType;
  description: string;
  acceptanceCriteria?: string[];
  branch?: string;
  autoApprove?: boolean;
  outputDir?: string;
  baseUrl?: string;
}

// ============================================================================
// Repository Types
// ============================================================================

/**
 * Repository information
 */
export interface RepositoryInfo {
  path: string;
  name: string;
  branch: string;
  remote?: string;
}

/**
 * File change information
 */
export interface FileChange {
  path: string;
  type: 'added' | 'modified' | 'deleted' | 'renamed';
  additions: number;
  deletions: number;
}

/**
 * Change set information
 */
export interface ChangeSet {
  files: FileChange[];
  summary: string;
  additions: number;
  deletions: number;
  diff: string;
}

// ============================================================================
// Test Context Types
// ============================================================================

/**
 * Complete test context
 */
export interface TestContext {
  repository: RepositoryInfo;
  changes: ChangeSet;
  description: string;
  acceptanceCriteria?: string[];
  buildInfo: BuildInfo;
}

/**
 * Build information
 */
export interface BuildInfo {
  framework: string;
  language: string;
  buildCommand?: string;
  testCommand?: string;
  startCommand?: string;
  port?: number;
  success: boolean;
  duration?: number;
  output?: string;
}

// ============================================================================
// Test Plan Types
// ============================================================================

/**
 * Test plan generated by the agent
 */
export interface TestPlan {
  id: string;
  testCases: TestCase[];
  estimatedDuration: number;
  requiredResources: string[];
  createdAt: string;
}

/**
 * Individual test case
 */
export interface TestCase {
  id: string;
  name: string;
  description: string;
  type: TestType;
  steps: TestStep[];
  expectedResult: string;
  priority?: 'high' | 'medium' | 'low';
}

/**
 * Test step within a test case
 */
export interface TestStep {
  action: string;
  target?: string;
  value?: string;
  description: string;
}

// ============================================================================
// Test Result Types
// ============================================================================

/**
 * Result of a single test case
 */
export interface TestResult {
  testCaseId: string;
  testCaseName: string;
  passed: boolean;
  duration: number;
  message: string;
  error?: string;
  screenshots?: string[];
  logs?: string[];
  timestamp: string;
  acceptanceCriterionId?: string;
}

/**
 * Summary of all test results
 */
export interface TestSummary {
  total: number;
  passed: number;
  failed: number;
  skipped: number;
  duration: number;
  successRate: number;
}

/**
 * Complete test results
 */
export interface TestResults {
  summary: TestSummary;
  results: TestResult[];
  duration: number;
  timestamp: string;
  repository: RepositoryInfo;
  testPlan: TestPlan;
}
// ============================================================================
// Acceptance Criteria Types
// ============================================================================

/**
 * Parsed acceptance criterion
 */
export interface AcceptanceCriterion {
  id: string;
  description: string;
  priority?: 'high' | 'medium' | 'low';
}

/**
 * Parsed acceptance criteria from markdown
 */
export interface ParsedAcceptanceCriteria {
  criteria: AcceptanceCriterion[];
  rawContent: string;
}

// ============================================================================
// Executable Test Types
// ============================================================================

/**
 * Executable HTTP test
 */
export interface ExecutableHTTPTest {
  id: string;
  acceptanceCriterionId: string;
  title: string;
  method: string;
  url: string;
  headers?: Record<string, string>;
  body?: any;
  expectedStatus: number;
  expectedBodyContains?: string[];
  expectedBodySchema?: any;
}

/**
 * Generated test artifacts
 */
export interface GeneratedTestArtifacts {
  qaTaskPlan: any;
  httpTests: ExecutableHTTPTest[];
  generatedAt: string;
  metadata: {
    totalTests: number;
    apiTests: number;
    manualTests: number;
  };
}


// ============================================================================
// CLI Prompt Types
// ============================================================================

/**
 * User input from CLI prompts
 */
export interface UserInput {
  repository: string;
  description: string;
  acceptanceCriteria?: string;
  testType: TestType;
  confirmed: boolean;
}

/**
 * Repository selection option
 */
export interface RepositoryOption {
  value: string;
  label: string;
  hint?: string;
}

// ============================================================================
// Error Types
// ============================================================================

/**
 * TraceQA error categories
 */
export enum ErrorCategory {
  CONFIGURATION = 'configuration',
  REPOSITORY = 'repository',
  BUILD = 'build',
  TEST_EXECUTION = 'test_execution',
  AGENT = 'agent',
  MCP = 'mcp',
  NETWORK = 'network',
  UNKNOWN = 'unknown'
}

/**
 * Custom error class for TraceQA
 */
export class TraceQAError extends Error {
  constructor(
    message: string,
    public category: ErrorCategory,
    public details?: unknown
  ) {
    super(message);
    this.name = 'TraceQAError';
  }
}

// ============================================================================
// Configuration Types
// ============================================================================

/**
 * TraceQA configuration
 */
export interface TraceQAConfig {
  ibmWatsonxApiKey?: string;
  defaultRepository?: string;
  mcpServers?: MCPServerConfig[];
  testTimeout?: number;
  maxRetries?: number;
  reportFormat?: 'json' | 'html' | 'markdown';
  outputDir?: string;
}

/**
 * TraceQA project configuration (from traceqa.config.json)
 */
export interface TraceQAProjectConfig {
  // API Configuration
  baseUrl?: string;
  healthUrl?: string;
  openapi?: string;

  // Build Configuration
  language?: string;
  projectType?: string;
  installCommand?: string;
  buildCommand?: string;
  startCommand?: string;

  // Build Flags
  autoInstall?: boolean;
  autoBuild?: boolean;
  autoStart?: boolean;

  // Test Configuration
  testType?: 'ui' | 'api' | 'both' | 'integration';
  outputDir?: string;
  timeout?: number;
  retries?: number;

  // IBM watsonx Configuration
  ibmWatsonxApiKey?: string;
  ibmWatsonxProjectId?: string;
  ibmWatsonxUrl?: string;
  ibmWatsonxModel?: string;
}

/**
 * MCP server configuration
 */
export interface MCPServerConfig {
  name: string;
  command: string;
  args?: string[];
  env?: Record<string, string>;
}

// ============================================================================
// Agent Types
// ============================================================================

/**
 * Agent configuration
 */
export interface AgentConfig {
  apiKey: string;
  model?: string;
  maxTokens?: number;
  temperature?: number;
  systemPrompt?: string;
  conversationHistory?: ConversationMessage[];
  timeout?: number;
  maxRetries?: number;
  streamResponses?: boolean;
}

/**
 * Agent state tracking
 */
export interface AgentState {
  currentPhase: 'planning' | 'executing' | 'analyzing' | 'reporting' | 'idle';
  conversationHistory: ConversationMessage[];
  testPlan?: TestPlan;
  executedTests: TestResult[];
  pendingDecisions: AgentDecision[];
  tokenUsage: TokenUsage;
  startTime: string;
  lastActivity: string;
}

/**
 * Conversation message for agent communication
 */
export interface ConversationMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
  metadata?: {
    tokenCount?: number;
    model?: string;
    finishReason?: string;
  };
}

/**
 * Token usage tracking
 */
export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  estimatedCost: number;
}

/**
 * Agent decision result
 */
export interface AgentDecision {
  action: 'approve' | 'modify' | 'reject' | 'ask_human' | 'retry' | 'continue' | 'abort';
  reasoning: string;
  suggestions?: string[];
  confidence: number;
  nextSteps?: string[];
  requiresHumanInput?: boolean;
  metadata?: Record<string, unknown>;
}

/**
 * Agent message for communication (legacy, use ConversationMessage)
 */
export interface AgentMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
}

/**
 * IBM watsonx.ai API response
 */
export interface WatsonxResponse {
  model_id: string;
  created_at: string;
  results: Array<{
    generated_text: string;
    generated_token_count: number;
    input_token_count: number;
    stop_reason: string;
  }>;
}

/**
 * IBM watsonx.ai streaming chunk
 */
export interface WatsonxStreamChunk {
  results?: Array<{
    generated_text?: string;
    generated_token_count?: number;
    input_token_count?: number;
    stop_reason?: string;
  }>;
  usage?: {
    input_tokens?: number;
    output_tokens?: number;
  };
}

/**
 * Test planning request
 */
export interface TestPlanningRequest {
  context: TestContext;
  requirements: string[];
  constraints?: {
    maxDuration?: number;
    maxTestCases?: number;
    priorityAreas?: string[];
  };
}

/**
 * Test execution request
 */
export interface TestExecutionRequest {
  testCase: TestCase;
  context: TestContext;
  retryCount?: number;
}

/**
 * Agent analysis result
 */
export interface AgentAnalysis {
  summary: string;
  findings: string[];
  recommendations: string[];
  risks: Array<{
    description: string;
    severity: 'low' | 'medium' | 'high' | 'critical';
    mitigation?: string;
  }>;
  confidence: number;
}

/**
 * Agent report generation options
 */
export interface ReportOptions {
  format: 'json' | 'html' | 'markdown';
  includeScreenshots?: boolean;
  includeLogs?: boolean;
  includeTokenUsage?: boolean;
  outputPath?: string;
}

// ============================================================================
// Utility Types
// ============================================================================

/**
 * Async operation result
 */
export type Result<T, E = Error> = 
  | { success: true; data: T }
  | { success: false; error: E };

/**
 * Progress callback type
 */
export type ProgressCallback = (message: string, percentage?: number) => void;

/**
 * Log level enumeration
 */
export enum LogLevel {
  DEBUG = 'debug',
  INFO = 'info',
  WARN = 'warn',
  ERROR = 'error',
  SUCCESS = 'success'
}

// ============================================================================
// Build System Types (Re-exported from core modules)
// ============================================================================

/**
 * Project types for framework detection
 */
export enum ProjectFramework {
  REACT = 'react',
  VUE = 'vue',
  ANGULAR = 'angular',
  NEXT = 'next',
  NUXT = 'nuxt',
  SVELTE = 'svelte',
  NODE_API = 'node-api',
  EXPRESS = 'express',
  FASTIFY = 'fastify',
  NEST = 'nest',
  UNKNOWN = 'unknown',
}

/**
 * Package managers
 */
export enum PackageManagerType {
  NPM = 'npm',
  YARN = 'yarn',
  PNPM = 'pnpm',
  BUN = 'bun',
}

/**
 * Build modes
 */
export enum BuildMode {
  DEVELOPMENT = 'development',
  PRODUCTION = 'production',
  PREVIEW = 'preview',
}

// ============================================================================
// MCP (Model Context Protocol) Types
// ============================================================================

/**
 * Browser action enumeration for MCP operations
 */
export enum BrowserAction {
  NAVIGATE = 'navigate',
  CLICK = 'click',
  TYPE = 'type',
  SCREENSHOT = 'screenshot',
  WAIT_FOR_ELEMENT = 'waitForElement',
  EVALUATE = 'evaluate',
  FILL = 'fill',
  SELECT = 'select',
  HOVER = 'hover',
  PRESS = 'press',
  GO_BACK = 'goBack',
  GO_FORWARD = 'goForward',
  RELOAD = 'reload',
  CLOSE = 'close'
}

/**
 * MCP configuration interface
 */
export interface MCPConfig {
  enableBrowserMCP?: boolean;
  enablePlaywrightMCP?: boolean;
  servers?: MCPServerConfig[];
  timeout?: number;
  retryAttempts?: number;
  retryDelay?: number;
  headless?: boolean;
  slowMo?: number;
  viewport?: {
    width: number;
    height: number;
  };
}

/**
 * MCP tool request interface
 */
export interface MCPToolRequest {
  serverName: string;
  toolName: string;
  arguments: Record<string, unknown>;
  timeout?: number;
}

/**
 * MCP tool response interface
 */
export interface MCPToolResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  metadata?: {
    duration: number;
    timestamp: string;
    serverName: string;
    toolName: string;
  };
}

/**
 * Browser state interface
 */
export interface BrowserState {
  url: string;
  title: string;
  isNavigating: boolean;
  viewport: {
    width: number;
    height: number;
  };
  cookies?: Array<{
    name: string;
    value: string;
    domain: string;
  }>;
  localStorage?: Record<string, string>;
  sessionStorage?: Record<string, string>;
}

/**
 * Browser navigation options
 */
export interface NavigationOptions {
  url: string;
  waitUntil?: 'load' | 'domcontentloaded' | 'networkidle0' | 'networkidle2';
  timeout?: number;
}

/**
 * Element selector options
 */
export interface SelectorOptions {
  selector: string;
  timeout?: number;
  visible?: boolean;
  state?: 'attached' | 'detached' | 'visible' | 'hidden';
}

/**
 * Screenshot options
 */
export interface ScreenshotOptions {
  path?: string;
  fullPage?: boolean;
  type?: 'png' | 'jpeg';
  quality?: number;
  clip?: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
}

/**
 * MCP server connection status
 */
export enum MCPConnectionStatus {
  DISCONNECTED = 'disconnected',
  CONNECTING = 'connecting',
  CONNECTED = 'connected',
  ERROR = 'error',
  RECONNECTING = 'reconnecting'
}

/**
 * MCP server info
 */
export interface MCPServerInfo {
  name: string;
  status: MCPConnectionStatus;
  capabilities: string[];
  version?: string;
  lastConnected?: string;
  errorCount: number;
}

/**
 * Browser type enumeration
 */
export enum BrowserType {
  CHROMIUM = 'chromium',
  FIREFOX = 'firefox',
  WEBKIT = 'webkit'
}

/**
 * Playwright-specific configuration
 */
export interface PlaywrightConfig {
  browserType: BrowserType;
  headless?: boolean;
  slowMo?: number;
  devtools?: boolean;
  args?: string[];
  ignoreHTTPSErrors?: boolean;
  downloadsPath?: string;
  proxy?: {
    server: string;
    username?: string;
    password?: string;
  };
}

/**
 * Network interception options
 */
export interface NetworkInterceptionOptions {
  patterns?: string[];
  blockResources?: ('image' | 'stylesheet' | 'font' | 'script' | 'xhr' | 'fetch')[];
  modifyResponses?: Array<{
    urlPattern: string;
    status?: number;
    body?: string;
    headers?: Record<string, string>;
  }>;
}

/**
 * MCP operation result with retry information
 */
export interface MCPOperationResult<T = unknown> extends MCPToolResponse<T> {
  attempts: number;
  totalDuration: number;
  retried: boolean;
}

// ============================================================================
// API Testing Types
// ============================================================================

/**
 * HTTP methods for API testing
 */
export enum HTTPMethod {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
  PATCH = 'PATCH',
  HEAD = 'HEAD',
  OPTIONS = 'OPTIONS'
}

/**
 * Authentication types for API requests
 */
export enum AuthType {
  NONE = 'none',
  BEARER = 'bearer',
  BASIC = 'basic',
  API_KEY = 'api_key',
  CUSTOM = 'custom'
}

/**
 * API authentication configuration
 */
export interface APIAuth {
  type: AuthType;
  token?: string;
  username?: string;
  password?: string;
  apiKey?: string;
  apiKeyHeader?: string;
  customHeaders?: Record<string, string>;
}

/**
 * API request configuration
 */
export interface APIRequest {
  method: HTTPMethod;
  url: string;
  headers?: Record<string, string>;
  body?: unknown;
  params?: Record<string, string>;
  auth?: APIAuth;
  timeout?: number;
  validateSSL?: boolean;
}

/**
 * API response data
 */
export interface APIResponse<T = unknown> {
  status: number;
  statusText: string;
  headers: Record<string, string>;
  body: T;
  duration: number;
  timestamp: string;
}

/**
 * API assertion types
 */
export enum AssertionType {
  STATUS_CODE = 'status_code',
  HEADER = 'header',
  BODY_CONTAINS = 'body_contains',
  BODY_EQUALS = 'body_equals',
  BODY_MATCHES = 'body_matches',
  JSON_PATH = 'json_path',
  RESPONSE_TIME = 'response_time',
  CUSTOM = 'custom'
}

/**
 * API assertion configuration
 */
export interface APIAssertion {
  type: AssertionType;
  expected: unknown;
  actual?: unknown;
  path?: string;
  operator?: 'equals' | 'contains' | 'matches' | 'lessThan' | 'greaterThan';
  message?: string;
}

/**
 * API test configuration
 */
export interface APITestConfig {
  name: string;
  description?: string;
  request: APIRequest;
  assertions: APIAssertion[];
  retries?: number;
  retryDelay?: number;
  continueOnFailure?: boolean;
}

/**
 * API test result
 */
export interface APITestResult {
  testName: string;
  passed: boolean;
  request: APIRequest;
  response?: APIResponse;
  assertions: Array<{
    assertion: APIAssertion;
    passed: boolean;
    message: string;
  }>;
  error?: string;
  duration: number;
  timestamp: string;
  retryCount: number;
}

// ============================================================================
// Test Execution Types
// ============================================================================

/**
 * Test execution mode
 */
export enum TestExecutionMode {
  SEQUENTIAL = 'sequential',
  PARALLEL = 'parallel',
  MIXED = 'mixed'
}

/**
 * Test execution options
 */
export interface TestExecutionOptions {
  mode?: TestExecutionMode;
  maxParallel?: number;
  timeout?: number;
  retries?: number;
  retryDelay?: number;
  continueOnFailure?: boolean;
  captureScreenshots?: boolean;
  captureLogs?: boolean;
  generateReport?: boolean;
  reportFormat?: 'json' | 'html' | 'markdown';
  outputDir?: string;
}

/**
 * Test execution status
 */
export enum TestExecutionStatus {
  PENDING = 'pending',
  RUNNING = 'running',
  PASSED = 'passed',
  FAILED = 'failed',
  SKIPPED = 'skipped',
  TIMEOUT = 'timeout',
  ERROR = 'error'
}

/**
 * Test execution progress
 */
export interface TestExecutionProgress {
  total: number;
  completed: number;
  passed: number;
  failed: number;
  skipped: number;
  current?: string;
  percentage: number;
  estimatedTimeRemaining?: number;
}

/**
 * Test coordinator configuration
 */
export interface TestCoordinatorConfig {
  buildSystem?: {
    autoInstall?: boolean;
    autoBuild?: boolean;
    autoStart?: boolean;
    port?: number;
  };
  agent?: AgentConfig;
  mcp?: MCPConfig;
  execution?: TestExecutionOptions;
  cleanup?: {
    stopServer?: boolean;
    cleanupMCP?: boolean;
    saveResults?: boolean;
  };
  baseUrl?: string;
  healthUrl?: string;
}

/**
 * Test coordinator state
 */
export interface TestCoordinatorState {
  phase: 'idle' | 'initializing' | 'building' | 'planning' | 'executing' | 'analyzing' | 'reporting' | 'cleanup' | 'error';
  buildResult?: {
    success: boolean;
    serverUrl?: string;
    port?: number;
  };
  testPlan?: TestPlan;
  executionProgress?: TestExecutionProgress;
  results?: TestResults;
  error?: string;
  startTime?: string;
  endTime?: string;
}

/**
 * Web test action types
 */
export enum WebTestAction {
  NAVIGATE = 'navigate',
  CLICK = 'click',
  TYPE = 'type',
  FILL = 'fill',
  SELECT = 'select',
  HOVER = 'hover',
  PRESS = 'press',
  WAIT = 'wait',
  WAIT_FOR_ELEMENT = 'waitForElement',
  WAIT_FOR_NAVIGATION = 'waitForNavigation',
  SCREENSHOT = 'screenshot',
  ASSERT_TEXT = 'assertText',
  ASSERT_VISIBLE = 'assertVisible',
  ASSERT_ENABLED = 'assertEnabled',
  ASSERT_URL = 'assertUrl',
  EVALUATE = 'evaluate',
  GO_BACK = 'goBack',
  GO_FORWARD = 'goForward',
  RELOAD = 'reload'
}

/**
 * Web test step configuration
 */
export interface WebTestStep {
  action: WebTestAction;
  selector?: string;
  value?: string;
  timeout?: number;
  description: string;
  screenshot?: boolean;
  continueOnFailure?: boolean;
}

/**
 * Web test configuration
 */
export interface WebTestConfig {
  name: string;
  description?: string;
  url: string;
  steps: WebTestStep[];
  viewport?: {
    width: number;
    height: number;
  };
  timeout?: number;
  retries?: number;
}

/**
 * Web test result
 */
export interface WebTestResult {
  testName: string;
  passed: boolean;
  steps: Array<{
    step: WebTestStep;
    passed: boolean;
    duration: number;
    error?: string;
    screenshot?: string;
  }>;
  screenshots: string[];
  error?: string;
  duration: number;
  timestamp: string;
}

// ============================================================================
// Reporting Types
// ============================================================================

/**
 * Trace matrix entry mapping acceptance criteria to tests
 */
export interface TraceMatrixEntry {
  acceptanceCriterion: string;
  generatedTests: string[];
  executionResults: {
    testId: string;
    testName: string;
    status: 'passed' | 'failed' | 'uncertain';
    evidence?: string;
  }[];
  coverage: 'full' | 'partial' | 'none';
}

/**
 * Complete trace matrix for requirement traceability
 */
export interface TraceMatrix {
  entries: TraceMatrixEntry[];
  totalCriteria: number;
  coveredCriteria: number;
  coveragePercentage: number;
}

/**
 * Merge readiness assessment score
 */
export interface MergeReadinessScore {
  score: number; // 0-100
  recommendation: 'safe_to_merge' | 'review_needed' | 'do_not_merge';
  factors: {
    passedTests: number;
    failedTests: number;
    uncertainTests: number;
    coveragePercentage: number;
    criticalFailures: number;
  };
  risks: string[];
  summary: string;
}

/**
 * Complete report data structure
 */
export interface ReportData {
  metadata: {
    generatedAt: string;
    traceqaVersion: string;
    projectName: string;
    repository: RepositoryInfo;
  };
  testResults: TestResults;
  traceMatrix: TraceMatrix;
  mergeReadiness: MergeReadinessScore;
}
/**
 * Ambiguity detection types
 */
export interface AmbiguityIssue {
  criterion: string;
  issue: string;
  vagueTerms: string[];
  suggestion: string;
  severity: 'high' | 'medium' | 'low';
}

export interface AmbiguityAnalysis {
  totalCriteria: number;
  issuesFound: number;
  issues: AmbiguityIssue[];
  overallQuality: 'good' | 'fair' | 'poor';
}

/**
 * Git diff analysis types
 */
export interface GitFileChange {
  path: string;
  type: 'added' | 'modified' | 'deleted';
  linesAdded: number;
  linesDeleted: number;
}

export interface DiffAnalysis {
  baseBranch: string;
  changedFiles: GitFileChange[];
  impactedAreas: string[];
  riskLevel: 'high' | 'medium' | 'low';
  suggestedTestFocus: string[];
}


// Made with Bob
